
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 14;
  public static final int MENOR = 12;
  public static final int PUNTOYCOMA = 8;
  public static final int ARR = 20;
  public static final int DOSPUNTOS = 5;
  public static final int IGUAL = 9;
  public static final int CHAR = 17;
  public static final int ID = 4;
  public static final int NUMERODECIMAL = 3;
  public static final int COMA = 7;
  public static final int MAYOR = 13;
  public static final int EOF = 0;
  public static final int PRINTLN = 21;
  public static final int PARENTESIS_C = 11;
  public static final int error = 1;
  public static final int PARENTESIS_A = 10;
  public static final int ENTERO = 2;
  public static final int CORCHETE_C = 16;
  public static final int CORCHETE_A = 15;
  public static final int DOBLEDOSPUNTOS = 6;
  public static final int VAR = 19;
  public static final int DOUBLE = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "NUMERODECIMAL",
  "ID",
  "DOSPUNTOS",
  "DOBLEDOSPUNTOS",
  "COMA",
  "PUNTOYCOMA",
  "IGUAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "MENOR",
  "MAYOR",
  "GUION",
  "CORCHETE_A",
  "CORCHETE_C",
  "CHAR",
  "DOUBLE",
  "VAR",
  "ARR",
  "PRINTLN"
  };
}

