
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 25;
  public static final int AND = 21;
  public static final int MENOR = 12;
  public static final int DIFERENCIA = 17;
  public static final int PUNTOYCOMA = 8;
  public static final int CADENA = 30;
  public static final int DOSPUNTOS = 5;
  public static final int OR = 20;
  public static final int MENORIGUAL = 18;
  public static final int IGUAL = 9;
  public static final int NOT = 23;
  public static final int POTENCIA = 29;
  public static final int MODULO = 28;
  public static final int POR = 26;
  public static final int ID = 4;
  public static final int NUMERODECIMAL = 3;
  public static final int CARACTER = 31;
  public static final int COMA = 7;
  public static final int MAYOR = 13;
  public static final int EOF = 0;
  public static final int PRINTLN = 32;
  public static final int DIV = 27;
  public static final int MAYORIGUAL = 19;
  public static final int PARENTESIS_C = 11;
  public static final int error = 1;
  public static final int PARENTESIS_A = 10;
  public static final int DOBLEIGUAL = 16;
  public static final int XOR = 22;
  public static final int ENTERO = 2;
  public static final int CORCHETE_C = 15;
  public static final int CORCHETE_A = 14;
  public static final int DOBLEDOSPUNTOS = 6;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "NUMERODECIMAL",
  "ID",
  "DOSPUNTOS",
  "DOBLEDOSPUNTOS",
  "COMA",
  "PUNTOYCOMA",
  "IGUAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "MENOR",
  "MAYOR",
  "CORCHETE_A",
  "CORCHETE_C",
  "DOBLEIGUAL",
  "DIFERENCIA",
  "MENORIGUAL",
  "MAYORIGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MODULO",
  "POTENCIA",
  "CADENA",
  "CARACTER",
  "PRINTLN"
  };
}

